pipelines:
  - name: pipeline_custom_docker_image
    steps:
      - name: custom_docker_image
        type: Bash
        configuration:
          inputResources:
            - name: dbp_image
          runtime:
            type: image
            image:
              custom:
                name: $res_dbp_image_imageName
                tag: $res_dbp_image_imageTag
                registry: jfrog_artifactory_int
                sourceRepository: docker-local
                autoPull: true
        execution:
          onExecute:
            - echo $step_image_name
            - echo $step_image_tag
